### ISSUE TITLE
点击网页的play没反应啊

### ISSUE THREAD

**Issue by eee-du** [coolzilj/mama#1]
点击网页的play没反应啊

**Comment by eee-du** [comment]
Listening on port 1234
http://v.youku.com/v_show/id_XMTYzNzExNjA4MA==.html?f=27610037&from=y1.3-idx-beta-1519-23042.223465.4-1
Failed to start child process.

**Comment by coolzilj** [comment]
检查 youget 和 mpv 的路径对不对

**Comment by eee-du** [comment]
Listening on port 1234
http://v.youku.com/v_show/id_XMTU4MTgyNjcyMA==.html?from=y1.9-3.1
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at IncomingMessage.<anonymous> (/Users/Evin/Downloads/mama-master/server.js:23:20)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

**Comment by coolzilj** [comment]
提示文件权限出错，确保你的 youget、mpv有足够的权限执行。

先在 console 检查完整的命令能不能执行

```
/usr/local/bin/you-get --debug -p /usr/local/bin/mpv http://v.youku.com/v_show/id_XMTU4MTgyNjcyMA==.html?from=y1.9-3.1
```

**Comment by eee-du** [comment]
显示
SyntaxError: Unexpected identifier 'debug'. Parse error.
eval
_evaluateOn
_evaluateAndWrap
evaluate

**Comment by coolzilj** [comment]
你的youget版本号？升级到最新版本看看
